import Head from 'next/head'
import MainLayout from '../components/main-layout';
import Sidebar from '../features/sidebar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Sidebar />
      </>
    </>
  )
}
Home.getLayout = function getLayout(page) {
  return <MainLayout>{page}</MainLayout>
}