import Head from 'next/head'
import MainLayout from '../components/main-layout'
import Navbar from '../features/navbar'
import Content from "../features/content"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="wrap">
        <Navbar />
        <Content />
      </main>
    </>
  )
}
Home.getLayout = function getLayout(page) {
  return <MainLayout>{page}</MainLayout>
}